#!/bin/bash

# run OPC tool
SOURCE_DIR=/Users/heatherwelch/Dropbox/OPC_Farallons/github/OPC_Farallons/Operationalizing_V2
FILE_DIR=/Users/heatherwelch/Dropbox/OPC_Farallons/operationalization

cd /Users/heatherwelch/Dropbox/OPC_Farallons/operationalization/end_products_final
/opt/homebrew/bin/git-auto-sync sync

